**Conceptos basicos de algebra lineal**

https://numpy.org/doc/stable/reference/routines.array-creation.html *rutinas para crear np.arrays*

-Escalares, Vectores, Matrices, Tensores

Los **escalares** son simplemente un numero, que usualmente contienen arreglos de muchos numeros. Se suele escribir en formato *italica*, y como nombre de variable se suele colocar una letra en minuscula.

In [39]:
import numpy as np
import random as random
random.seed(1)

In [40]:
# ejemplo de un escalar
s = np.array(-1) # se suele definir con 's' cuando es un numero real (s = ± ∞)
n = np.array(3) # se suele definir con 'n' cuando es un numero natural (n > 0)
print('la dimension de "s" es: {}, al igual que el de "n"'.format(s.ndim))
print('el tamaño de "n" es: {}, al igual que el de "s"'.format(n.size))
print('los escalares entonces son {} de 0 dimension, sin forma, y de tamaño 1'.format(type(n)))

la dimension de "s" es: 0, al igual que el de "n"
el tamaño de "n" es: 1, al igual que el de "s"
los escalares entonces son <class 'numpy.ndarray'> de 0 dimension, sin forma, y de tamaño 1


***
Los **vectores** son una matriz de 1 dimension (array de numeros), normalmente estas variables se suelen nombrar tambien con minusculas, y se suele anotar en los papers en ***italica y negrita*** por ejemplo ***x***

In [41]:
# ejemplo de un vector
x = np.array([1, 2, 3, 4, 5])
print('la dimension de "x" es: {}'.format(x.ndim))
print('el tamaño de "x" es: {}'.format(x.size))
print('los vectores entonces son {} de {} dimension, con variables formas ({}), y de tamaño ({}) variables'.format(type(x), x.ndim, x.shape, x.size))

la dimension de "x" es: 1
el tamaño de "x" es: 5
los vectores entonces son <class 'numpy.ndarray'> de 1 dimension, con variables formas ((5,)), y de tamaño (5) variables


***
Las **matrices** son arrays de 2 dimensiones (*axes*), cada elemento dentro de la matriz es identificado con dos indices. Las variables se suelen llamar con mayusculas. En los papers se denotan en mayusculas, italicas y negritas (***X***)

In [43]:
# ejemplo de una matriz
X = np.ones((2, 3)) # en este caso cree una matriz cuya forma es de 2 filas y 3 columnas
print(X)
print('la dimension de "X" es: {}'.format(X.ndim))
print('el tamaño de "X" es: {}'.format(X.size))
print('los vectores entonces son {} de {} dimensiones, con variables formas ({}), y de tamaño ({}) variables'.format(type(X), X.ndim, X.shape, X.size))

[[1. 1. 1.]
 [1. 1. 1.]]
la dimension de "X" es: 2
el tamaño de "X" es: 6
los vectores entonces son <class 'numpy.ndarray'> de 2 dimensiones, con variables formas ((2, 3)), y de tamaño (6) variables


***
Los **tensores** son arrays de mas de 2 dimensiones. Se denota en los papers en mayusculas, sin italicas, y en negritas (**A**)

In [49]:
T = np.full((2, 3, 2), 3)
print(T)
print('la dimension de "T" es: {}'.format(T.ndim))
print('el tamaño de "T" es: {}'.format(T.size))
print('los vectores entonces son {} de {} dimensiones, con variables formas ({}), y de tamaño ({}) variables'.format(type(T), T.ndim, T.shape, T.size))

[[[3 3]
  [3 3]
  [3 3]]

 [[3 3]
  [3 3]
  [3 3]]]
la dimension de "T" es: 3
el tamaño de "T" es: 12
los vectores entonces son <class 'numpy.ndarray'> de 3 dimensiones, con variables formas ((2, 3, 2)), y de tamaño (12) variables


***
Otro concepto importante para los arrays se puede decir que es la transferencia, esto hace que la matriz se voltee desde la diagonal principal (top izq a btn der) y se denota con una "T"


$A$  as $A^T$ 

La formula es la siguiente: 

$(A^T)_{i,j} = A_{i,j}$


***
**El caso en las matrices ndim = 2**

In [71]:
# vamos a aplicar la formula a una matriz de dos dimensiones con datos generados al azar
R = np.random.randint(0, high=10, size=(5,2))
print(R)
RT = np.transpose(R)
print(RT)
# haciendo un test para verificar si entendi el concepto y como se opera este
R_wb = np.array([[2, 3, 4], [5, 6, 7], [8, 9, 10]])
print(R_wb)
RT_wb = np.transpose(R_wb)
print(RT_wb)

[[1 8]
 [5 4]
 [7 6]
 [9 4]
 [7 0]]
[[1 5 7 9 7]
 [8 4 6 4 0]]
[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
[[ 2  5  8]
 [ 3  6  9]
 [ 4  7 10]]


***
**El caso en las tensores ndim = 3**

In [96]:
# vamos a aplicar la formula a una matriz de tres dimensiones con datos generados al azar
TT = np.random.randint(0, high=10, size=(5,2,2))
# print(TT)
TTT = np.transpose(TT)
# print(TTT)
# haciendo un test para verificar si entendi el concepto y como se opera este
TT_wb = np.array([[[2, 3, 4, 90], [5, 6, 7, 91], [10, 11, 12, 92]], [[13, 14, 15, 93], [16, 17, 18, 94], [19, 20, 21, 95]]])
# print(TT_wb)
print(TT_wb.shape)
print(TT_wb[1][1][3])
# probando con tensores
TTT_wb = np.transpose(TT_wb)
# print(TTT_wb)
print(TTT_wb[3][1][1])

# en el caso de los tensores de 3 diemensiones nos podemos dar cuenta que cuando se hace una transposicion se hace de la siguinte manera, manteniendo la dimension
# de las filas de forma intacta e intercambiando la dimensiones de la columna y tensor, pienso que esta funcion nos podria funcionar para el tratamiento de las 
# imagenes.

(2, 3, 4)
94
94


***
**El caso en las vectores y escalares ndim = 1, ndim = 0**

In [108]:
v = np.random.randint(0, high = 3, size = (3))
vT = np.transpose(v)
print(v)
print(vT)

# escalar ya definido
print(s)
sT = np.transpose(s)
print(s)

[1 1 1]
[1 1 1]
-1
-1


***
**Operaciones basicas entre matrices**

La suma entre matrices se puede hacer sin ningun problema, siempre y cuando ambas matrices tengan la misma forma
A.ndim = n
B.ndim = n

***C*** = ***A***+***B***

$C_{i,j} = A_{i,j} + B_{i,j}$

*ValueError: operands could not be broadcast together with shapes (2,3) (2,4)* (error cuando se opera matrices de diferente forma)

In [115]:
# suma entre matrices de la misma dimension
A = np.random.randint(1, high=6, size=(2, 3))
B = np.random.randint(1, high=6, size=(2, 3))
C = A+B
print(C)

[[6 7 6]
 [5 7 2]]


***
Tambien se pueden operar sumando una matriz con un escalar (el escalar afectara a cada uno de los elementos de la matriz)

D = A + b

$C_{i,j} = A_{i,j} + b$

Como tambien se puede multiplicar por un escalar

$E_{i,j} = A_{i,j} * b$

In [125]:
# sumando una matriz por un escalar
D = A + 3
print(A)
print(D)

# multiplicando una  matriz por un escalar
E = A * 3
print(E)

# lo mismo pasa con los tensores
T = np.ones((3, 2, 5))
print(T*3)

[[4 3 5]
 [4 2 1]]
[[7 6 8]
 [7 5 4]]
[[12  9 15]
 [12  6  3]]
[[[3. 3. 3. 3. 3.]
  [3. 3. 3. 3. 3.]]

 [[3. 3. 3. 3. 3.]
  [3. 3. 3. 3. 3.]]

 [[3. 3. 3. 3. 3.]
  [3. 3. 3. 3. 3.]]]


***
**Broadcastin** es un concepto que se usa en el aprendizaje profundo, que se logra sumando un vector en una matriz, basicamente el vector que tiene que tener la forma al igual que la columna de la matriz 

In [134]:
# ingresando un vector en una matriz de dos dimensiones
v = np.random.randint(1, 3,(3))
print(v)
F = C+v
print(F)

[1 1 2]
[[7 8 8]
 [6 8 4]]
